---
title: "Quarto Report"
format:
  html:
    toc: true
    echo: false
    keep-hidden: true
execute: 
  echo: false
---

# Examples

A simple R plot is shown here @fig-r.

```{r}
#| label: fig-r
#| fig-cap: "This is a simple R plot"

plot(1:10)
```

# Interactivity

```{ojs}
//| panel: input
viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)
viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe", "Dream"], 
    label: "Islands:"}
)
viewof island_select = Inputs.select(
  islands, 
  { label: "Location:"}
)
```

::: {.panel-tabset}

# Plot

```{ojs}
Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass_g", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```

# Data

```{ojs}
Inputs.table(filtered)
```

:::

```{ojs}
data = FileAttachment("./palmer-penguins.csv").csv({ typed: true })
```

```{ojs}
filtered = data.filter(function(penguin) {
  return bill_length_min < penguin.bill_length_mm &&
         island_select.includes(penguin.island);
})
```

```{r}
#| label: fig-r-margin
#| fig-cap: "This is a simple R plot"
#| fig-column: margin

plot(1:100)
```

::: {.column-margin}
This is a sidenote.
:::